export const mockData = {
  generatedAt: new Date().toISOString(),
  overview: {
    status: 'online',
    runtime: 'OpenClaw main',
    channel: 'webchat',
    activeSessions: 4,
    activeTasks: 2,
    errors: 1,
    totalVisibleTokens: 246381,
  },
  activeWork: [
    {
      id: 'sess-main',
      title: 'Main session',
      kind: 'direct',
      state: 'active',
      model: 'gpt-5.4',
      tokens: 19092,
      contextPct: 7,
      updatedAt: 'just now',
      summary: 'Analizando configuración y corrigiendo cron de Telegram.',
    },
    {
      id: 'sess-telegram',
      title: 'Telegram coding session',
      kind: 'direct',
      state: 'active',
      model: 'gpt-5.4-mini',
      tokens: 202000,
      contextPct: 74,
      updatedAt: '1 min ago',
      summary: 'Sesión grande con trabajo sostenido; vigilar compactación/contexto.',
    },
  ],
  cron: [
    {
      id: 'telegram-project-night-watch',
      enabled: true,
      status: 'ok',
      nextRun: 'in 1h 56m',
      lastRun: 'ok',
      detail: 'Entrega validada a Telegram chat 2091740588.',
    },
    {
      id: 'clawflows-scheduler',
      enabled: true,
      status: 'ok',
      nextRun: 'in 12m',
      lastRun: 'ok',
      detail: 'Scheduler activo cada 15 minutos.',
    },
  ],
  timeline: [
    { id: 1, type: 'fix', time: '06:32', text: 'Cron de Telegram inspeccionado por error de outbound.' },
    { id: 2, type: 'patch', time: '06:33', text: 'Se fijó delivery explícito a canal telegram y chat 2091740588.' },
    { id: 3, type: 'run', time: '06:33', text: 'Ejecución manual del cron forzada para validación.' },
    { id: 4, type: 'ok', time: '06:33', text: 'Run entregado correctamente: deliveryStatus=delivered.' },
  ],
  logs: [
    '[info] OpenClaw gateway reachable',
    '[info] Telegram channel ON / OK',
    '[warn] One session near high context usage (74%)',
    '[info] Cron telegram-project-night-watch delivered successfully',
  ],
}
